### DISCUSSION TITLE
NNODES_RUN_FCST in task_run_fcst

### DISCUSSION THREAD

**Discussion by SarahLu-NOAA** [ufs-community/ufs-srweather-app#1000] [Q&A] [answered]
Hi, UFS/SRW experts -

I created a new grid (12 km over NE US) at Derecho with SRW v2.2 public release.   The new grid is specified in task_make_grid section in config.yaml.  I also specify WRTCMP related parameters in task_run_fcst section.   The SRW experiments with the new grid went well.  I then add this new grid to PREDEF_GRID_NAME by updating valid_param_vals.yaml and predef_grid_params.yaml.  The parameters removed from config.yaml and added to predef_grid_params.yaml are listed at the end of the msg.     The experiment is halted at the fcst step.  FV3LAM_wflow.log shows: 

**Submission of run_fcst_mem000 failed!  qsub: directive error: -l select={{ task_run_fcst.NNODES_RUN_FCST // 1 }}:mpiprocs=128:ncpus=128**

var_defns.sh in the failed SRW run shows  
NNODES_RUN_FCST='{{ (PE_MEMBER01 + PPN_RUN_FCST - 1) // PPN_RUN_FCST }}'
var_defns.sh in the previous SRW run (when new grid is specified in config.yaml) shows
NNODES_RUN_FCST='1'

My quick fix is to hardcode NNODES_RUN_FCST to 1 in config.yaml and the SRW exp now runs ok.
My question is: why these changes related to new grid affects how NNODES_RUN_FCST is setup in the workflow?

Thanks -Sarah

  GRID_GEN_METHOD: ESGgrid
  ESGgrid_LON_CTR: -78.
  ESGgrid_LAT_CTR:  44.
  ESGgrid_DELX: 12000.0
  ESGgrid_DELY: 12000.0
  ESGgrid_NX: 200
  ESGgrid_NY: 140
  ESGgrid_WIDE_HALO_WIDTH: 6
  ESGgrid_PAZI: 0.0
  DT_ATMOS: 60
  LAYOUT_X: 4
  LAYOUT_Y: 4
  BLOCKSIZE: 32
  QUILTING:
   WRTCMP_write_groups: 1
   WRTCMP_write_tasks_per_group: '{{ LAYOUT_Y }}'
   WRTCMP_output_grid: lambert_conformal
   WRTCMP_cen_lon: '{{ task_make_grid.ESGgrid_LON_CTR }}'
   WRTCMP_cen_lat: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
   WRTCMP_lon_lwr_left: -91.6565
   WRTCMP_lat_lwr_left: 35.8696
   WRTCMP_stdlat1: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
   WRTCMP_stdlat2: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
   WRTCMP_nx: 198
   WRTCMP_ny: 138
   WRTCMP_dx: 12000.0
   WRTCMP_dy: 12000.0

**Comment by gspetro-NOAA** [comment]
Hi @SarahLu-NOAA ,

Just wanted to let you know that I am working on getting a subject matter expert (SME) to assist with your question. Hopefully we can get you an answer by early next week, but in the meantime, I didn't want to leave you hanging. 

Best,
Gillian Petro

**Comment by MichaelLueken** [comment]
Hello @SarahLu-NOAA -

I was able to replicate what you are seeing with your new grid, but using the `RRFS_CONUS_25km` grid instead.  I set this grid as follows:
```
"RRFS_CONUS_25km":
  GRID_GEN_METHOD: "ESGgrid"
  ESGgrid_LON_CTR: -97.5
  ESGgrid_LAT_CTR: 38.5
  ESGgrid_DELX: 25000.0
  ESGgrid_DELY: 25000.0
  ESGgrid_NX: 219
  ESGgrid_NY: 131
  ESGgrid_PAZI: 0.0
  ESGgrid_WIDE_HALO_WIDTH: 6
  DT_ATMOS: 150
  LAYOUT_X: 5
  LAYOUT_Y: 2
  BLOCKSIZE: 40
  QUILTING:
    WRTCMP_write_groups: 1
    WRTCMP_write_tasks_per_group: '{{ LAYOUT_Y }}'
    WRTCMP_output_grid: "lambert_conformal"
    WRTCMP_cen_lon: '{{ task_make_grid.ESGgrid_LON_CTR }}'
    WRTCMP_cen_lat: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
    WRTCMP_stdlat1: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
    WRTCMP_stdlat2: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
    WRTCMP_nx: 217
    WRTCMP_ny: 128
    WRTCMP_lon_lwr_left: -122.719528
    WRTCMP_lat_lwr_left: 21.138123
    WRTCMP_dx: 25000.0
    WRTCMP_dy: 25000.0
```
Upon doing so, the `var_defns.sh` file is showing:

`NNODES_RUN_FCST='{{ (PE_MEMBER01 + PPN_RUN_FCST - 1) // PPN_RUN_FCST }}'`

and the test failed with `qsub: directive error: -l select={{ task_run_fcst.NNODES_RUN_FCST // 1 }}:mpiprocs=128:ncpus=128`.

I was able to correct this behavior by setting `WRTCMP_write_tasks_per_group: 2`.

In order to correct this, you will need to set `WRTCMP_write_tasks_per_group: 4` in your `ush/predef_grid_params.yaml` file.

Please let me know if you continue to encounter this issue even with this modification.
