### DISCUSSION TITLE
Is there a way to disable run_post task in the workflow (I'm using the develop branch)

### DISCUSSION THREAD

**Discussion by padhrigmccarthy** [ufs-community/ufs-srweather-app#848] [Q&A] [answered]
Hi- 

I'm using the develop branch for some work at NCAR on Online-CMAQ, and I see that the config param RUN_TASK_RUN_POST: has gone away in recent months. I don't see any equivalent in config_defaults.yaml -- the only mention is that using  WRITE_DOPOST: true will disable the run_post task. But I do not need WRITE_DOPOST. Is there any way to turn off run_post without enabling some other post-processing step?

Thank you, 

-Paddy McCarthy.

**Comment by gspetro-NOAA** [comment, marked as answer]
Hi Paddy,

Yes! There has been a restructuring of the workflow recently, and documentation is still catching up. Now, workflow tasks live in the `parm/wflow` yaml files. In `config.yaml`, you can set which of these files/tasks run in the `rocoto: tasks: taskgroups:` section: 

```
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml", "parm/wflow/plot.yaml"]|include }}'
```
To turn off run_post, I believe you just remove the `parm/wflow/post.yaml` from the list of taskgroups to run. 

Hope this helps!

Best,
Gillian Petro | EPIC Advanced User Support Team

**Comment by padhrigmccarthy** [comment]
Thank you for the tip Gillian!

This worked just as you described. 

I wanted to add one piece of info to this thread, for future readers. If you enable a taskgroup, but don't want all the child tasks to execute, the solution is to add those tasks as parameters with empty values. 

My example may not apply to all users, because it's for running Online-CMAQ. But the same principle applies. Here, we needed to run `pre_post_stat`, which is part of the `aqm_post` taskgroup. I added aqm_post to the taskgroups: config, then looked in parm/wflow/aqm_post.yaml and got the names of the other tasks, which I turned off with blank param lines, like so:

```
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml", "parm/wflow/aqm_post.yaml"]|include }}'
    task_post_stat_o3:
    task_post_stat_pm25:
    task_bias_correction_o3:
    task_bias_correction_pm25:
```

Thank you again for the pointer, 

-Paddy.
