### ISSUE TITLE
Default UFS-Fire config needs update for uwtools integration

### ISSUE THREAD

**Issue by benkozi** [ufs-community/ufs-srweather-app#1277]
## Expected behavior

`config.fire.yaml` will run the experiment as documented.

## Current behavior

The current configuration file results in UFS-Fire being disabled:
```
UFS_FIRE is not enabled; setting FIRE_NUM_TASKS = 0
```

The `envvars` section of the fire configuration needs to be updated to:
```
fire:
  envvars:
    UFS_FIRE: True
    FIRE_INPUT_DIR: '{{ platform.WE2E_TEST_DATA }}/UFS_FIRE/{{ workflow.DATE_FIRST_CYCL }}'
...
```

## Machines affected
All
