### ISSUE TITLE
EXTRN_MDL_ICS_TIMEOFFSET_HRS does not work for GFS data (nemsio or netcdf)

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#456]
## Expected behavior
When `EXTRN_MDL_ICS_TIMEOFFSET_HRS` is set with `EXTRN_MDL_NAME_ICS: FV3GFS` and `FV3GFS_FILE_FMT_ICS: nemsio (or netcdf)` in `config.yaml`, the gfs data files for atm and sfc in the previous cycle should be retrieved. 

## Current behavior
The `make_ics` task failed due to a missing `sfcfXXX' file.

## Steps To Reproduce
Set the following in `config.yaml`:
```
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: netcdf
  EXTRN_MDL_ICS_OFFSET_HRS: 6
```
