### ISSUE TITLE
Variable forecast length broken when cycles start at later times.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#743]
## Expected behavior

The variable forecast length feature should work no matter the start/end dates of the experiment.

## Current behavior

The behavior of the workflow configuration settings controlling variable forecast lengths at different lead times requires that cycles be defined in strictly increasing order after PR #722.

For example, if the user wanted to run at 06 UTC and 18 UTC cycles for 3 days, and run a 18 hour forecast at 06 UTC and a 72 hour forecast at 18 UT cycles, the experiment start date MUST be a 06 UTC cycle. The scripts do not support starting at 18 UTC for this configuration.

Generally speaking, to support variable forecast lengths, the experiment start date must be consistent with the desired forecast length array start cycle. 

This should not impact the ability to run all forecasts with the same length.

## Machines affected

All machines.

## Steps To Reproduce

Bad behavior will be present in run-time scripts when running a configuration like this:

```
  DATE_FIRST_CYCL: '2023021718'
  DATE_LAST_CYCL: '2023021906'
  INCR_CYCL_FREQ: 12
  FCST_LEN_HRS: -1
  FCST_LEN_CYCL:
    - 72
    - 18
```

In any cycle that is less than 18 UTC, a negative list index for `FCST_LEN_CYCL` will be produced.
