### ISSUE TITLE
[production/AQM.v7] compath.py utility is required to define environmental variables in support of AQMv7 implementation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#747]
We have been using the SRW workflow to support AQM or Online-CMAQ as one of the UFS applications since June 1,st 2022. Now we need to transition the UFS-AQM or Online-CMAQ to operation. To meet NCO implementation standards,  we need to use "compath.py" utility to define environmental variables such as COMIN, COMOUT, COMINgfs, COMINgefs, etc. It is seen in the JREGIONAL_AQM_LBCS and JREGIONAL_NEXUS_GFS_SFC, but not for other jobs for defining $COMIN and $COMOUT.  Please see more details or examples on Page 8 of NCEP Central Operations WCOSS Implementation Standards below

https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf

**Comment by danielabdi-noaa** [comment]
@JianpingHuang-NOAA Note that SRW does call `compath.py` on wcoss2 specifically for COMIN/COMINgfs etc
```
data:
  ics_lbcs:
    GSMGFS: compath.py ${envir}/gsmgfs/${gsmgfs_ver}/gsmgfs.${PDYext}
    FV3GFS: compath.py ${envir}/gfs/${gfs_ver}/gfs.${PDYext}/${cycext}/atmos
    RAP: compath.py ${envir}/rap/${rap_ver}/rap.${PDYext}
    NAM: compath.py ${envir}/nam/${nam_ver}/nam.${PDYext}
    HRRR: compath.py ${envir}/hrrr/${hrrr_ver}/hrrr.${PDYext}/conus
```
These will be evaluated in `exregional_get_extrn_mdl_files.sh`
