### ISSUE TITLE
No error or warning when entries in `data_locations.yml` are missing; documentation for modifying `data_locations.yml` missing

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#856]
## Description

 
When modifying `data_locations.yml` to add a new archive file template to search for in HPSS (e.g. because HPSS updated its file naming convention), one's natural inclination is to append the template to the existing list.  E.g., if that section of the file looks like:
```
  hpss:
    protocol: htar
    archive_path:
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
    archive_internal_dir:
      - ./gfs.{yyyymmdd}/{hh}
      - ./gfs.{yyyymmdd}/{hh}/atmos
    archive_file_names:
      grib2:
        anl:
          - gpfs_dell1_nco_ops_com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.2_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.3_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
        fcst:
          - gpfs_dell1_nco_ops_com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.2_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.3_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
```
then to add a new forecast template (say `abcd_{yyyymmdd}_{hh}.tar`), one might modify the above as follows (note the new bolded line at the end):
<pre>
  hpss:
    protocol: htar
    archive_path:
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
      - /NCEPPROD/hpssprod/runhistory/rh{yyyy}/{yyyymm}/{yyyymmdd}
    archive_internal_dir:
      - ./gfs.{yyyymmdd}/{hh}
      - ./gfs.{yyyymmdd}/{hh}/atmos
    archive_file_names:
      grib2:
        anl:
          - gpfs_dell1_nco_ops_com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.2_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.3_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
        fcst:
          - gpfs_dell1_nco_ops_com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_prod_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.2_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - com_gfs_v16.3_gfs.{yyyymmdd}_{hh}.gfs_pgrb2.tar
          - <b>abcd_{yyyymmdd}_{hh}.tar</b>
</pre>
But apparently this is not sufficient because a corresponding path entry needs to be added to the `archive_path:` section (and an entry may also need to be added to the `archive_internal_dir:` section; I'm not sure).  However, if this is not done, the code does not error out (nor issue a warning).   I also could not find a description of the expected behavior in the SRW App documentation.

## Solution

There are two possible solutions:
1) Exit with an error message indicating that the 5th entry under `fcst:` does not have a matching entry under `archive_path:` (and wherever else entries are needed).
2) Try applying the first four paths under `archive_path:` to the 5th entry under `fcst:` (i.e. try all possible combinations of `archive_path` and `fcst` until a match is found in HPSS; if no combinations work, error out).

In either case, the documentation should be updated to describe all the fields that must be supplied when modifying the `data_locations.yml` file.

## Requirements**

No software version updates are required.

## Acceptance Criteria (Definition of Done)

When a user only appends an entry under `fcst:` (or `anl:`) without adding a path under `archive_path:`, the code should either try the existing entries under `archive_path` with the new entry under `fcst` (or `anl`), or it should fail and let the user know what additional entries are needed in `data_locations.yml`.
